

services:
  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: futureme-api
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=oracle
      - QUARKUS_DATASOURCE_USERNAME=rm563509
      - QUARKUS_DATASOURCE_PASSWORD=140607
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      - QUARKUS_HTTP_PORT=8080
